version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    privileged: true
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/:/var/log/nginx
    networks:
      - app_net
    # 容器名称
    container_name: "mrmoll-nginx"

  php56:
    build:
      context: ./build/php/php56
      dockerfile: Dockerfile
    image: mrmoll:php56-fpm-alpine
    expose:
      - "9000"
    privileged: true
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf/php/php56/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php56/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php/:/var/log/php-fpm
    networks:
      - app_net
    container_name: "mrmoll-php56"

  php71:
    build:
      context: ./build/php/php71
      dockerfile: Dockerfile
    image: mrmoll:php71-fpm-alpine
    expose:
      - "9000"
    privileged: true
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf/php/php71/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php71/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php/:/var/log/php-fpm
    networks:
      - app_net
    container_name: "mrmoll-php71"
  mysql57:
    image: mysql:5.7
    ports:
      - "3306:3306"
    privileged: true
    volumes:
      - ./conf/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./conf/mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./data/mysql/:/var/lib/mysql/
      - ./log/mysql/:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - app_net
    # 容器名称
    container_name: "mrmoll-mysql57"
networks:
  # 配置docker network
  app_net:
    driver: bridge
    ipam:
      config:
      # 子网络
      - subnet: 10.10.0.0/16
